sudo: required
services:
  - docker

before_install:
  - docker build -t vverma/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vverma/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app:  "docker-react"
  env:  "docker-react-env"
  bucket_name:  "elasticbeanstalk-ap-south-1-795735340981"
  bucket_path:  "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
    